import type { IconSvgElement } from "@hugeicons/react";
import {
  AdvertisimentIcon,
  AiIdeaIcon,
  Award02Icon,
  BookOpen01Icon,
  Briefcase01Icon,
  Building06Icon,
  Calculator01Icon,
  Calendar03Icon,
  CameraVideoIcon,
  CapIcon,
  ChartIncreaseIcon,
  CouponPercentIcon,
  FileSearchIcon,
  FlowchartIcon,
  GiftCardIcon,
  HoodieIcon,
  Home09Icon,
  ImageUpload01Icon,
  InstagramIcon,
  LeftToRightListDashIcon,
  Linkedin01Icon,
  Linkedin02Icon,
  Mail01Icon,
  Megaphone01Icon,
  MessageMultiple01Icon,
  Mic01Icon,
  NewTwitterIcon,
  Package01Icon,
  PinterestIcon,
  Presentation01Icon,
  QuoteDownCircleIcon,
  QuoteUpCircleIcon,
  QuoteUpIcon,
  Rocket01Icon,
  ShoppingBag02Icon,
  SlidersHorizontalIcon,
  SparklesIcon,
  Store01Icon,
  Sun03Icon,
  Tag01Icon,
  TShirtIcon,
  UserGroupIcon,
  UserMultiple02Icon,
  VideoReplayIcon,
  YoutubeIcon,
} from "@hugeicons/core-free-icons";

/** Unique platform/category icons for Studio presets (no duplicates). */
export const PRESET_ICONS = {
  linkedinPost: Linkedin01Icon,
  instagramStory: CameraVideoIcon,
  instagramPost: InstagramIcon,
  xPost: NewTwitterIcon,
  youtubeThumbnail: YoutubeIcon,
  pinterestPin: PinterestIcon,
  linkedinBanner: Linkedin02Icon,
  socialMediaAd: Megaphone01Icon,
  displayBanner: AdvertisimentIcon,
  customerTestimonial: QuoteDownCircleIcon,
  professionalInsight: AiIdeaIcon,
  microPost: MessageMultiple01Icon,
  communityPost: UserMultiple02Icon,
  promoHighlight: Tag01Icon,
  retailCampaign: Store01Icon,
  outdoorDisplay: Building06Icon,
  promoReward: CouponPercentIcon,
  productReveal: Rocket01Icon,
  eventPromo: Calendar03Icon,
  milestoneCelebration: Award02Icon,
  hiringPoster: Briefcase01Icon,
  launchTeaser: SparklesIcon,
  seasonalCampaign: Sun03Icon,
  blogCover: BookOpen01Icon,
  newsletterHeader: Mail01Icon,
  caseStudyCover: FileSearchIcon,
  podcastCover: Mic01Icon,
  presentationCover: Presentation01Icon,
  thoughtLeadership: QuoteUpIcon,
  teamSpotlight: UserGroupIcon,
  inspirationalQuote: QuoteUpCircleIcon,
  dataStory: ChartIncreaseIcon,
  processExplainer: FlowchartIcon,
  comparisonChart: LeftToRightListDashIcon,
  statHighlight: Calculator01Icon,
  socialHeader: ImageUpload01Icon,
  heroImage: ImageUpload01Icon,
  channelArt: VideoReplayIcon,
  productHero: Package01Icon,
  lifestyleScene: Home09Icon,
  hoodieMockup: HoodieIcon,
  apparelTee: TShirtIcon,
  toteMockup: ShoppingBag02Icon,
  capMockup: CapIcon,
  customPack: SlidersHorizontalIcon,
} as const satisfies Record<string, IconSvgElement>;
